name: DevOps Pipeline

on:
  push:
    branches:
      - main  # Ejecutar cuando se realiza un push a la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      - name: Create credentials file
        run: |
          cat > credentials.ini <<EOF
          [credentials]
          username = ${{ secrets.USERNAME }}
          password = ${{ secrets.PASSWORD }}
          EOF

      - name: Copy Dockerfile
        run: cp Dockerfile $GITHUB_WORKSPACE/

      - name: Build docker image
        run: docker build -t devops_ws . --tag devops_ws_$(date +%s) $GITHUB_WORKSPACE/
